"""empty message

Revision ID: 26d1e8296df6
Revises: 
Create Date: 2021-04-08 19:26:52.535032

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '26d1e8296df6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SingleCard', 'cardCollectionID',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SingleCard', 'cardCollectionID',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
