"""empty message

Revision ID: 2b417e9ad97f
Revises: 
Create Date: 2021-04-23 17:18:50.342296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b417e9ad97f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(), nullable=True),
    sa.Column('userPasswordHash', sa.String(), nullable=True),
    sa.Column('userInfo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_table('CardsCollection',
    sa.Column('collectionID', sa.Integer(), nullable=False),
    sa.Column('collectionName', sa.String(), nullable=True),
    sa.Column('collectionDescription', sa.JSON(), nullable=True),
    sa.Column('holderID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['holderID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('collectionID')
    )
    op.create_table('Card',
    sa.Column('cardID', sa.Integer(), nullable=False),
    sa.Column('collectionID', sa.Integer(), nullable=False),
    sa.Column('cardInside', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['collectionID'], ['CardsCollection.collectionID'], ),
    sa.PrimaryKeyConstraint('cardID')
    )
    op.create_table('UserCollectionInfo',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('collectionID', sa.Integer(), nullable=False),
    sa.Column('userCardInfo', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['collectionID'], ['CardsCollection.collectionID'], ),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('userID', 'collectionID')
    )
    op.create_table('CardWatched',
    sa.Column('cardWatchedID', sa.Integer(), nullable=False),
    sa.Column('cardID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cardID'], ['Card.cardID'], ),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ),
    sa.PrimaryKeyConstraint('cardWatchedID', 'cardID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CardWatched')
    op.drop_table('UserCollectionInfo')
    op.drop_table('Card')
    op.drop_table('CardsCollection')
    op.drop_table('User')
    # ### end Alembic commands ###
