"""empty message

Revision ID: 2e65f0d2f78b
Revises: 26d1e8296df6
Create Date: 2021-04-08 19:31:50.362215

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e65f0d2f78b'
down_revision = '26d1e8296df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Card',
                    sa.Column('cardID', sa.Integer(), nullable=False),
                    sa.Column('collectionID', sa.Integer(), nullable=False),
                    sa.Column('cardInside', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['collectionID'], ['CardsCollection.cardID'], ),
                    sa.PrimaryKeyConstraint('cardID')
                    )
    op.drop_table('SingleCard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SingleCard',
                    sa.Column('cardInfo', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('cardCollectionID', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('singleCardID', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['cardCollectionID'], ['CardsCollection.cardID'],
                                            name='SingleCard_cardCollectionID_fkey')
                    )
    op.drop_table('Card')
    # ### end Alembic commands ###
